ARG REGISTRY_URL
ARG VERSION

FROM ${REGISTRY_URL}/centreon-web-alma9:develop
ARG VERSION

RUN mkdir /tmp/rpms-centreon-cloud-extensions
COPY *.rpm /tmp/rpms-centreon-cloud-extensions/

COPY --chmod=755 ./.github/scripts/install-centreon-module.php /tmp/install-centreon-module.php
COPY --chown=apache:apache ./.github/scripts/license/epp.license /etc/centreon/license.d/epp.license

RUN bash -e <<EOF

rm -rf /var/cache/centreon/symfony/*
su - apache -s /bin/bash -c "/usr/share/centreon/bin/console cache:clear"

yum install -y /tmp/rpms-centreon-cloud-extensions/*.rpm
yum clean all

service mysql start
su -c "/tmp/install-centreon-module.php -b /usr/share/centreon/bootstrap.php -m centreon-license-manager" -s /bin/bash apache
su -c "/tmp/install-centreon-module.php -b /usr/share/centreon/bootstrap.php -m centreon-pp-manager" -s /bin/bash apache
su -c "/tmp/install-centreon-module.php -b /usr/share/centreon/bootstrap.php -m centreon-autodiscovery-server" -s /bin/bash apache
su -c "/tmp/install-centreon-module.php -b /usr/share/centreon/bootstrap.php -m centreon-cloud-extensions" -s /bin/bash apache
service mysql stop

EOF