ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye

RUN bash -e <<EOF

apt-get update

apt-get -y install \
    ca-certificates \
    git \
    make \
    sudo \
    zstd

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list

apt-get update

apt-get -y install nfpm

apt-get clean

EOF
